import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        {/* -- Manifold Connect Widget install -- */}
        <script src="https://connect.manifoldxyz.dev/2.0.13/connect.umd.min.js"></script>
        <link rel="stylesheet" href="https://connect.manifoldxyz.dev/2.0.13/connect.css"></link>
        {/* ~~ Marketplace Widget ~~ */}
        <script async src="https://marketplace.manifoldxyz.dev/latest/marketplace.umd.min.js"></script>
        <link rel="stylesheet" href="https://marketplace.manifoldxyz.dev/latest/marketplace.css" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <a href="https://docs.manifold.xyz/v/manifold-for-developers/client-widgets/overview">
            Manifold
          </a>
          <span> </span>
          Next.js Template
        </h1>
        <br />
        {/* -- Add Connect Widget component  --*/}
        <div  
          data-widget="m-connect"
          data-grant-type="token"
          data-client-id="b26f7ccf76221dc3ead994df950adeebd4da49e4f876ccf12fcc3c3264d5918d"  
          data-app-name="dg"  
          data-redirect-uri="https://davidgan.xyz/"
          data-network="1"
          //// Optional Button Settings
          data-multi="true" // have WalletConnect as an option
          data-fallback-provider="wss://eth-mainnet.g.alchemy.com/v2/YAf6oc1YMm-1ubCZigOoM3Sy8Rl8akIg"
          data-show-chain="true" // show chain name
          data-show-balance="true" // show balance of wallet
          data-override-connect-text="Connect Your Wallet" // Text on button
        >  
        </div>
        
        <br />
        <br />
        {/* ~~ Add Marketplace Widget component ~~ */}
        <div
          data-widget="m-layout-complete-listing"
          data-id="444"
          data-network="1"
        ></div>
      </main>
    </div>
  )
}
